# Default values for formscriberApi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: formscriber.azurecr.io/formscriberapi
  tag: 0.2
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  paths: 
    - /(.*)
  hosts:
    - formscriber-umgc.eastus.cloudapp.azure.com
  tls: 
   - secretName: tls-secret
     hosts:
       - formscriber-umgc.eastus.cloudapp.azure.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
