apiVersion: v1
kind: Service
metadata:
  name: {{ include "formscriberApi.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "formscriberApi.name" . }}
    helm.sh/chart: {{ include "formscriberApi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "formscriberApi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
